name: places
description: A new places project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: any

  # Provides internationalization and localization facilities, including
  # message translation, plurals and genders, date/number formatting and
  # parsing, and bidirectional text.
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/catalog/

  fonts:
    - family: "Roboto"
      fonts:
        - asset: "res/Roboto-Regular.ttf"
          style: normal
        - asset: "res/Roboto-Italic.ttf"
          style: italic
